# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Houtan Bastani
email: houtan@dynare.org
description: >- # this means to ignore newlines until "baseurl:"
  Houtan Bastani's website CV resume scientific numericas programming mac macOS
permalink: ':title/'
baseurl: "/houtan" # the subpath of your site, e.g. /blog
url: "http://www.dynare.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  houtanb

# Author Settings
author: Houtan Bastani
author-img: houtanb.png
about-author: Research Software Engineer and Jeweler
social-instagram: hbcreated
social-github: houtanb
social-linkedin: houtanb
social-email: houtan@dynare.org

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jemoji

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
